# -*- coding: utf-8 -*-
"""meu.app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTDqrszOalaV48YP8KceSWnYuuF1WZUP
"""

import streamlit as st

st.title("Dashboard Power BI no Streamlit")

st.components.v1.html("""
<iframe title="ANALISE_EXPLORATORIA" width="600" height="373.5"
src="https://app.powerbi.com/view?r=eyJrIjoiNGI5ZDYyZGEtNGY5NC00NzZmLTgyYjItYjMyMGQ1NDYwZmQyIiwidCI6ImUxNTYzMmU1LTBiZWUtNDA5Ny04ZjM0LTNiY2NmZDUwOTE1OSJ9"
frameborder="0" allowFullScreen="true"></iframe>
""", height=400)